window.COUNTRY_LIST = [
  { name: "Afghanistan", code: "af", label: "Afghanistan (AF)" },
  { name: "Albania", code: "al", label: "Albania (AL)" },
  { name: "Algeria", code: "dz", label: "Algeria (DZ)" },
  { name: "Andorra", code: "ad", label: "Andorra (AD)" },
  { name: "Angola", code: "ao", label: "Angola (AO)" },
  { name: "Antigua and Barbuda", code: "ag", label: "Antigua and Barbuda (AG)" },
  { name: "Argentina", code: "ar", label: "Argentina (AR)" },
  { name: "Armenia", code: "am", label: "Armenia (AM)" },
  { name: "Australia", code: "au", label: "Australia (AU)" },
  { name: "Austria", code: "at", label: "Austria (AT)" },
  { name: "Azerbaijan", code: "az", label: "Azerbaijan (AZ)" },
  { name: "Bahamas", code: "bs", label: "Bahamas (BS)" },
  { name: "Bahrain", code: "bh", label: "Bahrain (BH)" },
  { name: "Bangladesh", code: "bd", label: "Bangladesh (BD)" },
  { name: "Barbados", code: "bb", label: "Barbados (BB)" },
  { name: "Belarus", code: "by", label: "Belarus (BY)" },
  { name: "Belgium", code: "be", label: "Belgium (BE)" },
  { name: "Belize", code: "bz", label: "Belize (BZ)" },
  { name: "Benin", code: "bj", label: "Benin (BJ)" },
  { name: "Bhutan", code: "bt", label: "Bhutan (BT)" },
  { name: "Bolivia", code: "bo", label: "Bolivia (BO)" },
  { name: "Bosnia and Herzegovina", code: "ba", label: "Bosnia and Herzegovina (BA)" },
  { name: "Botswana", code: "bw", label: "Botswana (BW)" },
  { name: "Brazil", code: "br", label: "Brazil (BR)" },
  { name: "Brunei", code: "bn", label: "Brunei (BN)" },
  { name: "Bulgaria", code: "bg", label: "Bulgaria (BG)" },
  { name: "Burkina Faso", code: "bf", label: "Burkina Faso (BF)" },
  { name: "Burundi", code: "bi", label: "Burundi (BI)" },
  { name: "Cabo Verde", code: "cv", label: "Cabo Verde (CV)" },
  { name: "Cambodia", code: "kh", label: "Cambodia (KH)" },
  { name: "Cameroon", code: "cm", label: "Cameroon (CM)" },
  { name: "Canada", code: "ca", label: "Canada (CA)" },
  { name: "Central African Republic", code: "cf", label: "Central African Republic (CF)" },
  { name: "Chad", code: "td", label: "Chad (TD)" },
  { name: "Chile", code: "cl", label: "Chile (CL)" },
  { name: "China", code: "cn", label: "China (CN)" },
  { name: "Colombia", code: "co", label: "Colombia (CO)" },
  { name: "Comoros", code: "km", label: "Comoros (KM)" },
  { name: "Congo (Congo-Brazzaville)", code: "cg", label: "Congo (Congo-Brazzaville) (CG)" },
  { name: "Congo (DRC)", code: "cd", label: "Congo (DRC) (CD)" },
  { name: "Costa Rica", code: "cr", label: "Costa Rica (CR)" },
  { name: "Croatia", code: "hr", label: "Croatia (HR)" },
  { name: "Cuba", code: "cu", label: "Cuba (CU)" },
  { name: "Cyprus", code: "cy", label: "Cyprus (CY)" },
  { name: "Czechia", code: "cz", label: "Czechia (CZ)" },
  { name: "Denmark", code: "dk", label: "Denmark (DK)" },
  { name: "Djibouti", code: "dj", label: "Djibouti (DJ)" },
  { name: "Dominica", code: "dm", label: "Dominica (DM)" },
  { name: "Dominican Republic", code: "do", label: "Dominican Republic (DO)" },
  { name: "Ecuador", code: "ec", label: "Ecuador (EC)" },
  { name: "Egypt", code: "eg", label: "Egypt (EG)" },
  { name: "El Salvador", code: "sv", label: "El Salvador (SV)" },
  { name: "Equatorial Guinea", code: "gq", label: "Equatorial Guinea (GQ)" },
  { name: "Eritrea", code: "er", label: "Eritrea (ER)" },
  { name: "Estonia", code: "ee", label: "Estonia (EE)" },
  { name: "Eswatini", code: "sz", label: "Eswatini (SZ)" },
  { name: "Ethiopia", code: "et", label: "Ethiopia (ET)" },
  { name: "Fiji", code: "fj", label: "Fiji (FJ)" },
  { name: "Finland", code: "fi", label: "Finland (FI)" },
  { name: "France", code: "fr", label: "France (FR)" },
  { name: "Gabon", code: "ga", label: "Gabon (GA)" },
  { name: "Gambia", code: "gm", label: "Gambia (GM)" },
  { name: "Georgia", code: "ge", label: "Georgia (GE)" },
  { name: "Germany", code: "de", label: "Germany (DE)" },
  { name: "Ghana", code: "gh", label: "Ghana (GH)" },
  { name: "Greece", code: "gr", label: "Greece (GR)" },
  { name: "Grenada", code: "gd", label: "Grenada (GD)" },
  { name: "Guatemala", code: "gt", label: "Guatemala (GT)" },
  { name: "Guinea", code: "gn", label: "Guinea (GN)" },
  { name: "Guinea-Bissau", code: "gw", label: "Guinea-Bissau (GW)" },
  { name: "Guyana", code: "gy", label: "Guyana (GY)" },
  { name: "Haiti", code: "ht", label: "Haiti (HT)" },
  { name: "Honduras", code: "hn", label: "Honduras (HN)" },
  { name: "Hong Kong", code: "hk", label: "Hong Kong (HK)" },
  { name: "Hungary", code: "hu", label: "Hungary (HU)" },
  { name: "Iceland", code: "is", label: "Iceland (IS)" },
  { name: "India", code: "in", label: "India (IN)" },
  { name: "Indonesia", code: "id", label: "Indonesia (ID)" },
  { name: "Iran", code: "ir", label: "Iran (IR)" },
  { name: "Iraq", code: "iq", label: "Iraq (IQ)" },
  { name: "Ireland", code: "ie", label: "Ireland (IE)" },
  { name: "Israel", code: "il", label: "Israel (IL)" },
  { name: "Italy", code: "it", label: "Italy (IT)" },
  { name: "Jamaica", code: "jm", label: "Jamaica (JM)" },
  { name: "Japan", code: "jp", label: "Japan (JP)" },
  { name: "Jordan", code: "jo", label: "Jordan (JO)" },
  { name: "Kazakhstan", code: "kz", label: "Kazakhstan (KZ)" },
  { name: "Kenya", code: "ke", label: "Kenya (KE)" },
  { name: "Kiribati", code: "ki", label: "Kiribati (KI)" },
  { name: "North Korea", code: "kp", label: "North Korea (KP)" },
  { name: "South Korea", code: "kr", label: "South Korea (KR)" },
  { name: "Kuwait", code: "kw", label: "Kuwait (KW)" },
  { name: "Kyrgyzstan", code: "kg", label: "Kyrgyzstan (KG)" },
  { name: "Laos", code: "la", label: "Laos (LA)" },
  { name: "Latvia", code: "lv", label: "Latvia (LV)" },
  { name: "Lebanon", code: "lb", label: "Lebanon (LB)" },
  { name: "Lesotho", code: "ls", label: "Lesotho (LS)" },
  { name: "Liberia", code: "lr", label: "Liberia (LR)" },
  { name: "Libya", code: "ly", label: "Libya (LY)" },
  { name: "Liechtenstein", code: "li", label: "Liechtenstein (LI)" },
  { name: "Lithuania", code: "lt", label: "Lithuania (LT)" },
  { name: "Luxembourg", code: "lu", label: "Luxembourg (LU)" },
  { name: "Madagascar", code: "mg", label: "Madagascar (MG)" },
  { name: "Malawi", code: "mw", label: "Malawi (MW)" },
  { name: "Malaysia", code: "my", label: "Malaysia (MY)" },
  { name: "Maldives", code: "mv", label: "Maldives (MV)" },
  { name: "Mali", code: "ml", label: "Mali (ML)" },
  { name: "Malta", code: "mt", label: "Malta (MT)" },
  { name: "Marshall Islands", code: "mh", label: "Marshall Islands (MH)" },
  { name: "Mauritania", code: "mr", label: "Mauritania (MR)" },
  { name: "Mauritius", code: "mu", label: "Mauritius (MU)" },
  { name: "Mexico", code: "mx", label: "Mexico (MX)" },
  { name: "Micronesia", code: "fm", label: "Micronesia (FM)" },
  { name: "Moldova", code: "md", label: "Moldova (MD)" },
  { name: "Monaco", code: "mc", label: "Monaco (MC)" },
  { name: "Mongolia", code: "mn", label: "Mongolia (MN)" },
  { name: "Montenegro", code: "me", label: "Montenegro (ME)" },
  { name: "Morocco", code: "ma", label: "Morocco (MA)" },
  { name: "Mozambique", code: "mz", label: "Mozambique (MZ)" },
  { name: "Myanmar", code: "mm", label: "Myanmar (MM)" },
  { name: "Namibia", code: "na", label: "Namibia (NA)" },
  { name: "Nauru", code: "nr", label: "Nauru (NR)" },
  { name: "Nepal", code: "np", label: "Nepal (NP)" },
  { name: "Netherlands", code: "nl", label: "Netherlands (NL)" },
  { name: "New Zealand", code: "nz", label: "New Zealand (NZ)" },
  { name: "Nicaragua", code: "ni", label: "Nicaragua (NI)" },
  { name: "Niger", code: "ne", label: "Niger (NE)" },
  { name: "Nigeria", code: "ng", label: "Nigeria (NG)" },
  { name: "North Macedonia", code: "mk", label: "North Macedonia (MK)" },
  { name: "Norway", code: "no", label: "Norway (NO)" },
  { name: "Oman", code: "om", label: "Oman (OM)" },
  { name: "Pakistan", code: "pk", label: "Pakistan (PK)" },
  { name: "Palau", code: "pw", label: "Palau (PW)" },
  { name: "Panama", code: "pa", label: "Panama (PA)" },
  { name: "Papua New Guinea", code: "pg", label: "Papua New Guinea (PG)" },
  { name: "Paraguay", code: "py", label: "Paraguay (PY)" },
  { name: "Peru", code: "pe", label: "Peru (PE)" },
  { name: "Philippines", code: "ph", label: "Philippines (PH)" },
  { name: "Poland", code: "pl", label: "Poland (PL)" },
  { name: "Portugal", code: "pt", label: "Portugal (PT)" },
  { name: "Qatar", code: "qa", label: "Qatar (QA)" },
  { name: "Romania", code: "ro", label: "Romania (RO)" },
  { name: "Russia", code: "ru", label: "Russia (RU)" },
  { name: "Rwanda", code: "rw", label: "Rwanda (RW)" },
  { name: "Saint Kitts and Nevis", code: "kn", label: "Saint Kitts and Nevis (KN)" },
  { name: "Saint Lucia", code: "lc", label: "Saint Lucia (LC)" },
  { name: "Saint Vincent and the Grenadines", code: "vc", label: "Saint Vincent and the Grenadines (VC)" },
  { name: "Samoa", code: "ws", label: "Samoa (WS)" },
  { name: "San Marino", code: "sm", label: "San Marino (SM)" },
  { name: "Sao Tome and Principe", code: "st", label: "Sao Tome and Principe (ST)" },
  { name: "Saudi Arabia", code: "sa", label: "Saudi Arabia (SA)" },
  { name: "Senegal", code: "sn", label: "Senegal (SN)" },
  { name: "Serbia", code: "rs", label: "Serbia (RS)" },
  { name: "Seychelles", code: "sc", label: "Seychelles (SC)" },
  { name: "Sierra Leone", code: "sl", label: "Sierra Leone (SL)" },
  { name: "Singapore", code: "sg", label: "Singapore (SG)" },
  { name: "Slovakia", code: "sk", label: "Slovakia (SK)" },
  { name: "Slovenia", code: "si", label: "Slovenia (SI)" },
  { name: "Solomon Islands", code: "sb", label: "Solomon Islands (SB)" },
  { name: "Somalia", code: "so", label: "Somalia (SO)" },
  { name: "South Africa", code: "za", label: "South Africa (ZA)" },
  { name: "South Sudan", code: "ss", label: "South Sudan (SS)" },
  { name: "Spain", code: "es", label: "Spain (ES)" },
  { name: "Sri Lanka", code: "lk", label: "Sri Lanka (LK)" },
  { name: "Sudan", code: "sd", label: "Sudan (SD)" },
  { name: "Suriname", code: "sr", label: "Suriname (SR)" },
  { name: "Sweden", code: "se", label: "Sweden (SE)" },
  { name: "Switzerland", code: "ch", label: "Switzerland (CH)" },
  { name: "Syria", code: "sy", label: "Syria (SY)" },
  { name: "Taiwan", code: "tw", label: "Taiwan (TW)" },
  { name: "Tajikistan", code: "tj", label: "Tajikistan (TJ)" },
  { name: "Tanzania", code: "tz", label: "Tanzania (TZ)" },
  { name: "Thailand", code: "th", label: "Thailand (TH)" },
  { name: "Timor-Leste", code: "tl", label: "Timor-Leste (TL)" },
  { name: "Togo", code: "tg", label: "Togo (TG)" },
  { name: "Tonga", code: "to", label: "Tonga (TO)" },
  { name: "Trinidad and Tobago", code: "tt", label: "Trinidad and Tobago (TT)" },
  { name: "Tunisia", code: "tn", label: "Tunisia (TN)" },
  { name: "Turkey", code: "tr", label: "Turkey (TR)" },
  { name: "Turkmenistan", code: "tm", label: "Turkmenistan (TM)" },
  { name: "Tuvalu", code: "tv", label: "Tuvalu (TV)" },
  { name: "Uganda", code: "ug", label: "Uganda (UG)" },
  { name: "Ukraine", code: "ua", label: "Ukraine (UA)" },
  { name: "United Arab Emirates", code: "ae", label: "United Arab Emirates (AE)" },
  { name: "United Kingdom", code: "gb", label: "United Kingdom (GB)" },
  { name: "United States", code: "us", label: "United States (US)" },
  { name: "Uruguay", code: "uy", label: "Uruguay (UY)" },
  { name: "Uzbekistan", code: "uz", label: "Uzbekistan (UZ)" },
  { name: "Vanuatu", code: "vu", label: "Vanuatu (VU)" },
  { name: "Vatican City", code: "va", label: "Vatican City (VA)" },
  { name: "Venezuela", code: "ve", label: "Venezuela (VE)" },
  { name: "Vietnam", code: "vn", label: "Vietnam (VN)" },
  { name: "Yemen", code: "ye", label: "Yemen (YE)" },
  { name: "Zambia", code: "zm", label: "Zambia (ZM)" },
  { name: "Zimbabwe", code: "zw", label: "Zimbabwe (ZW)" },
];
