window.regionalTranslations = {
  "in": {
    "btn": "कैसे उपयोग करें",
    "html": "<h2>How to use FrankPass</h2>\n    <p><strong>फायदा: सिर्फ 1 या 2 आसान बातें याद रखकर, जीवन भर के लिए कभी हैक न होने वाले पासवर्ड बनाएं!</strong></p>\n    <p>यह टूल 100% स्टेटलेस (Stateless) है। यह आपका डेटा कहीं सेव नहीं करता। यदि आप बिलकुल वही जानकारी दोबारा डालेंगे, तो आपको हमेशा बिलकुल वही पासवर्ड मिलेगा।</p>\n    <h3>🔑 इनपुट्स को समझना</h3>\n    <ol>\n      <li><strong>Platform / Website Name (ज़रूरी):</strong> जो भी मेजर प्लेटफॉर्म्स हैं वो पहले से ही ऑप्शंस में हैं। बस 1-2 अक्षर टाइप करें और सही नाम सेलेक्ट कर लें। इससे स्पेलिंग की गलती नहीं होगी। अगर आपका प्लेटफॉर्म लिस्ट में नहीं है, तो आप वेबसाइट का नाम या URL (जैसे <code>facebook.com</code>) भी टाइप कर सकते हैं।</li>\n      <li><strong>Secret Personal Key (ज़रूरी):</strong> यह आपकी मास्टर चाबी है! इसे याद रखने के लिए आप अपने 2-3 दोस्तों के नाम मिला कर लिख सकते हैं, या अपना नाम + पसंदीदा फल + साल लिख सकते हैं।\n      <br><em>ध्यान दें: सिस्टम ऑटोमैटिक रूप से स्पेस हटा देता है और अक्षरों को छोटा कर देता है।</em></li>\n      <li><strong>Variant:</strong> अगर किसी साइट का नया पासवर्ड बनाना हो, तो बस Variant को 1 से बढ़ाकर 2 कर दें।</li>\n    </ol>\n    <p>💡 <b>प्लेटफॉर्म रिक्वेस्ट:</b> अगर आप चाहते हैं कि हम कोई खास प्लेटफॉर्म लिस्ट में जोड़ें, तो हमें <b>X (@FrankPass)</b> पर मेंशन करें या ईमेल द्वारा संपर्क करें। हम उसे जल्द से जल्द जोड़ने की कोशिश करेंगे।</p>\n    <h3>🛡️ क्या करें और क्या न करें</h3>\n    <ul>\n      <li><strong>करें:</strong> हमेशा अपना Secret Key और Variant याद रखें।</li>\n      <li><strong>न करें:</strong> कभी भी अपना मास्टर की (Secret Key) किसी को न बताएं।</li>\n      <li><strong>करें:</strong> अगर साइट छोटा पासवर्ड मांगे, तो Length स्लाइडर का उपयोग करें।</li>\n    </ul>",
    "breach_title": "डेटा लीक से सावधान रहें",
    "breach_body": "FrankPass 100% स्टेटलेस और ज़ीरो-नॉलेज टूल है। हमारे पास कोई डेटाबेस नहीं है, जिसका मतलब है कि हम आपका ईमेल इकट्ठा नहीं कर सकते और न ही आपको वेबसाइट हैक होने पर अलर्ट कर सकते हैं। <br><br> हालांकि, अगर आप ग्लोबल डेटा लीक के बारे में तुरंत फ्री अलर्ट चाहते हैं, तो हमारी मूल एजेंसी <strong>FrankBase Digital</strong> के आधिकारिक सुरक्षा न्यूज़लेटर से जुड़ें।"
  },
  "ng": {
    "btn": "How to Use",
    "html": "<h2>How to use FrankPass</h2>\n    <p><strong>Benefit: Remember just 1 or 2 things and generate unbreakable passwords for life!</strong></p>\n    <p>This tool is 100% stateless. It saves nothing anywhere. Enter the same details — get the exact same password every time.</p>\n    <h3>🔑 What to Fill In</h3>\n    <ol>\n      <li><strong>Platform / Website (Required):</strong> Major platforms are already in options. Just type 1-2 letters and select. If your platform is not listed, you can type any website name or URL (e.g., <code>example.com</code>).</li>\n      <li><strong>Secret Personal Key (Required):</strong> Your master phrase — anything you will never forget. You can use names of 2-3 friends or your name + favorite fruit + a year.\n      <br><em>Note: System automatically removes spaces and makes everything lowercase.</em></li>\n      <li><strong>Variant:</strong> Need a new password for the same site? Keep your key, just change Variant from 1 to 2.</li>\n    </ol>\n    <p>💡 <b>Request Platform:</b> If you want us to add a specific platform, mention us on <b>X (@FrankPass)</b> or send an email. We will try to add it as soon as possible.</p>\n    <h3>🛡️ Do's and Don'ts</h3>\n    <ul>\n      <li><strong>Do:</strong> Keep your Secret Key and Variant consistent for the same site.</li>\n      <li><strong>Don't:</strong> Never share your Master Key with anyone.</li>\n      <li><strong>Do:</strong> Use the Length slider if a site requires a shorter password.</li>\n    </ul>",
    "breach_title": "Beware of Data Breaches",
    "breach_body": "FrankPass is 100% Stateless and Zero-Knowledge. We don't have a database, which means we cannot collect your email or alert you when websites get hacked. <br><br> However, if you want free, instant alerts about global data breaches, join the official security newsletter by <strong>FrankBase Digital</strong>."
  },
  "us": {
    "btn": "Cómo utilizar",
    "html": "<h2>How to use FrankPass</h2>\n    <p><strong>Beneficio: ¡Recordando solo 1 o 2 cosas, puedes crear contraseñas irrompibles para toda la vida!</strong></p>\n    <p>Esta herramienta es 100% stateless. No guarda tus datos. Si introduces los mismos detalles, siempre obtendrás la misma contraseña.</p>\n    <h3>🔑 Entradas</h3>\n    <ol>\n      <li><strong>Plataforma / Sitio Web (Requerido):</strong> Las principales plataformas ya están en las opciones. Escribe 1-2 letras y selecciónala. Si no está en la lista, puedes escribir el nombre o la URL (ej. <code>facebook.com</code>).</li>\n      <li><strong>Secret Personal Key (Requerido):</strong> Tu frase maestra secreta. Algo que nunca olvides.</li>\n      <li><strong>Variant:</strong> Para crear una nueva contraseña en el mismo sitio, cambia este número de 1 a 2.</li>\n    </ol>\n    <p>💡 <b>Solicitar Plataforma:</b> Si quieres que añadamos una plataforma, menciónanos en <b>X (@FrankPass)</b> o envía un email.</p>\n    <h3>🛡️ Qué hacer y qué no hacer</h3>\n    <ul>\n      <li><strong>Hacer:</strong> Mantén tu Secret Key segura.</li>\n      <li><strong>No hacer:</strong> Nunca compartas tu Clave Maestra.</li>\n    </ul>",
    "breach_title": "Cuidado con las filtraciones de datos",
    "breach_body": "FrankPass es 100% Stateless. No tenemos base de datos, por lo que no podemos avisarte si un sitio es hackeado. <br><br> Para recibir alertas gratuitas sobre filtraciones globales, suscríbete al boletín de seguridad de <strong>FrankBase Digital</strong>."
  },
  "fr": {
    "btn": "Comment utiliser",
    "html": "<h2>How to use FrankPass</h2>\n    <p><strong>Avantage : En vous rappelant seulement 1 ou 2 choses simples, vous pouvez créer des mots de passe inviolables à vie!</strong></p>\n    <p>Cet outil est 100% stateless. Il n'enregistre rien nulle part.</p>\n    <h3>🔑 Comprendre les entrées</h3>\n    <ol>\n      <li><strong>Plateforme / Site Web (Requis):</strong> Les plateformes majeures sont déjà listées. Tapez 1-2 lettres et choisissez. Si absent, tapez le nom ou l'URL (ex. <code>google.com</code>).</li>\n      <li><strong>Secret Personal Key (Requis):</strong> Votre phrase principale Secrète.</li>\n      <li><strong>Variant:</strong> Pour un nouveau mot de passe, changez le numéro (ex. de 1 à 2).</li>\n    </ol>\n    <p>💡 <b>Demande de Plateforme :</b> Mentionnez-nous sur <b>X (@FrankPass)</b> ou contactez-nous par email.</p>\n    <h3>🛡️ À faire et à ne pas faire</h3>\n    <ul>\n      <li><strong>À faire:</strong> Gardez votre clé secrète mémorisée.</li>\n      <li><strong>À ne pas faire:</strong> Ne partagez jamais votre clé maître.</li>\n    </ul>",
    "breach_title": "Attention aux fuites de données",
    "breach_body": "FrankPass est 100% Stateless. Nous n'avons pas de base de données. Pour des alertes sur les fuites de données mondiales, rejoignez la newsletter de <strong>FrankBase Digital</strong>."
  }
};